# To better understand this file read this:
# https://docs.ionos.space/docs/github-actions-customization/

name: "Deploy Now: Execute Build"

on:
  workflow_call:
    inputs:
      site-url:
        required: true
        type: string
      branch-id:
        required: true
        type: string

env:
  DEPLOYMENT_FOLDER: public

jobs:
# Please do not rename this job
  build-project:
    name: build Lardevies
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: v24.x

      - name: Build Node assets
        env:
          CHAT_API_URL: https://onjwlzvlfuhleqlkscrx.supabase.co/functions/v1/chat
          CI: true
          SITE_URL: ${{ inputs.site-url }}
        run: |
          npm ci
          npm run build

# Please do not touch the following action
      - name: Store deployment content
        uses: ionos-deploy-now/artifact-action@v1
        with:
          api-key: ${{ secrets.IONOS_API_KEY }}
          service-host: api-eu.ionos.space
          project-id: bddec1b3-7ff9-41e5-983c-c40e342c059b
          branch-id: ${{ inputs.branch-id }}
          version: ${{ github.sha }}
          folder: ${{ env.DEPLOYMENT_FOLDER }}
          config-file: .deploy-now/Lardevies/config.yaml
          action: upload
